stages:
    - build
    - lint
    - deploy

before_script:
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME

build:
    image: gradle:7.4.2-jdk17-alpine
    stage: build
    script: gradle --build-cache assemble
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle

test1:
    image: gradle:7.4.2-jdk17-alpine
    stage: lint
    script:
        - gradle check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle

test2:
    image: node:18.14.2-alpine3.17
    stage: lint
    script:
        - npm install
        - npx eslint .
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - node_modules

deploy:
    stage: deploy
    script: echo "No deployment script"
    environment: production
