image: gradle:latest

before_script:
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME

build:
    stage: build
    script: gradle --build-cache assemble
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle

test:
    stage: test
    script:
        - gradle check
#        - eslint .
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle

deploy:
    stage: deploy
    script: echo "Warning - no deployment script"
    environment: production
