image: gradle:alpine

before_script:
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME

build:
    stage: build
    script: gradle --build-cache assemble
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle

test1:
    stage: test1
    script: gradle check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle

test2:
    stage: test2
    script: npg eslint .
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle

deploy:
    stage: deploy
    script: echo "Warning - no deployment script"
    environment: production
