version: "3.8"

services:
    sportgh-mysql:
        image: mysql:8.1.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: sportgh
            MYSQL_USER: sportgh
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"

    sportgh-frontend:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        restart: unless-stopped
        ports:
            - "4200:80"

    sportgh-backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://sportgh-mysql:3306/sportgh?autoReconnect=true&useSSL=false
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=1234
