# use this file with
#
#    docker compose -f compose.mysql.yml up --build
#

version: "3.8"

services:
    sportgh-mysql:
        image: mysql:5.7.24
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: sportgh
            MYSQL_USER: sportgh
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - "edu_cs_sportgh_mysql_volume:/var/lib/mysql"

    sportgh-frontend:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        restart: unless-stopped
        ports:
            - "4200:80"

    sportgh-backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=sportgh-mysql
            - DB_PORT=3306
            - DB_USERNAME=root
            - DB_PASSWORD=1234

volumes:
    edu_cs_sportgh_mysql_volume:

