FROM node:18.14.2-alpine3.17 as build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/*

COPY --from=build /usr/src/app/dist/webapp /usr/share/nginx/html

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]

