FROM node:18.14.2-alpine3.17 as build

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:stable-alpine3.17-slim

COPY --from=build /usr/src/app/dist/webapp /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

