# Stage 1: Build the application
FROM node:18.14.2-alpine3.17 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

# Stage 2: Serve the application with Nginx
FROM nginx:stable-alpine3.17-slim

# Copy the built static files from the build stage
COPY --from=build /app/dist/webapp /usr/share/nginx/html

# Copy your Nginx configuration
COPY nginx.config /etc/nginx/conf.d/default.conf

EXPOSE 4200

# Nginx will start automatically
