#DigitalOcean only
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ca-sportgh-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: sportgh.k8s.edu.codespring.ro
      http:
        paths:
          - path: /
            backend:
              serviceName: ca-sportgh-frontend-service
              servicePort: 80
    - host: api.sportgh.k8s.edu.codespring.ro
      http:
        paths:
          - path: /
            backend:
              serviceName: ca-sportgh-backend-service
              servicePort: 80
