apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-images-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
