apiVersion: apps/v1                                           #version of the API to use
kind: Deployment                                              #what kind of object we're deploying
metadata:                                                     #information about our object we're deploying
  name: ca-sportgh-backend-deployment                            #Name of the deployment
  labels:                                                     #a labels on the deployments created
    app: ca-sportgh-backend
spec:                                                         #specifications for our object
  replicas: 2                                                 #the number of pods that should always be running
  selector:                                                   #which pods the replica set should be responsible for
    matchLabels:
      app: ca-sportgh-backend                                    #any pods with labels matching this I'm responsible for
  template:                                                   #the pod template that gets deployed
    metadata:
      labels:                                                 #labels on the replica set and pods created
        app: ca-sportgh-backend
    spec:
      containers:
        - name: sportgh-backend                                    #the name of the container within the pod
          image: r.edu.codespring.ro/sportgh/sportgh-backend:ca-k8s   #which container image should be pulled
          imagePullPolicy: Always
          ports:
            - containerPort: 8080                                 #the port of the container within the pod
              protocol: TCP
      imagePullSecrets:
        - name: sportgh-group-registry

---
apiVersion: v1                                                #version of the API to use
kind: Service                                                 #what kind of object we're deploying
metadata:                                                     #information about our object we're deploying
  name: ca-sportgh-backend-service                               #Name of the service
  labels:
    app: ca-sportgh-backend
spec:                                                         #specifications for our object
  ports:                                                      #Ignore for now
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:                                                   #label selector used to identify pods
    app: ca-sportgh-backend
