auth:
  rootPassword: "sportghPass"
  database: "sportgh"
#persistence:
#  enabled: true
#  size: 10Gi
#resources:
#  requests:
#    memory: "512Mi"
#    cpu: "250m"
#  limits:
#    memory: "1Gi"
#    cpu: "500m"
