# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: ca-sportgh-mysql-service
  labels:
    app: ca-sportgh-mysql
    owner: ka
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: ca-sportgh-mysql
