apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-sportgh-mysql-configmap
  labels:
    app: ca-sportgh-mysql
    owner: ka
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
